"""statics

迁移 ID: 38b6c70555d6
父迁移: 9b1080fbd7d1
创建时间: 2025-05-23 09:58:59.666744

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '38b6c70555d6'
down_revision: str | Sequence[str] | None = '9b1080fbd7d1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('platform', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command_record', schema=None) as batch_op:
        batch_op.drop_column('platform')
        batch_op.drop_column('bot_id')

    # ### end Alembic commands ###
