"""km_push_record

迁移 ID: 9b1080fbd7d1
父迁移: d9827344f67e
创建时间: 2025-05-21 16:43:45.660981

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "9b1080fbd7d1"
down_revision: str | Sequence[str] | None = "d9827344f67e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("killmail_push_record", schema=None) as batch_op:
        batch_op.add_column(sa.Column("bot_id", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("platform", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("session_id", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("session_type", sa.String(), nullable=False))
        batch_op.drop_column("send_type")
        batch_op.drop_column("reason")
        batch_op.drop_column("sender")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("killmail_push_record", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sender", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("reason", sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column("send_type", sa.VARCHAR(), nullable=False))
        batch_op.drop_column("session_type")
        batch_op.drop_column("session_id")
        batch_op.drop_column("platform")
        batch_op.drop_column("bot_id")

    # ### end Alembic commands ###
