"""structure_notifications

迁移 ID: e3a7f1c24b90
父迁移: c1f4e79a0d12
创建时间: 2026-02-23

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "e3a7f1c24b90"
down_revision: str | Sequence[str] | None = "c1f4e79a0d12"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "structure_notification_sub",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("character_name", sa.String(length=128), nullable=False),
        sa.Column("platform", sa.String(length=64), nullable=False),
        sa.Column("bot_id", sa.String(length=128), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("session_type", sa.String(length=32), nullable=False),
        sa.Column("categories", sa.Text(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_structure_notification_sub")),
        sa.UniqueConstraint("character_id", "platform", "session_id", name="uq_struct_sub_char_session"),
    )
    with op.batch_alter_table("structure_notification_sub", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_structure_notification_sub_character_id"), ["character_id"], unique=False)

    op.create_table(
        "structure_notification_record",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("notification_id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("notification_type", sa.String(length=128), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("sender_type", sa.String(length=32), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("pushed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_structure_notification_record")),
        sa.UniqueConstraint("notification_id", "character_id", name="uq_struct_notif_id_char"),
    )
    with op.batch_alter_table("structure_notification_record", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_structure_notification_record_notification_id"), ["notification_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_structure_notification_record_character_id"), ["character_id"], unique=False)
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("structure_notification_record")
    op.drop_table("structure_notification_sub")
    # ### end Alembic commands ###
