name: 部署到 GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 构建 Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ./XiaoBaWang-docs/package-lock.json

      - name: 安装依赖
        run: |
          cd ./XiaoBaWang-docs
          npm install

      - name: 构建网站
        run: |
          cd ./XiaoBaWang-docs
          npm run build

      - name: 上传构建制品
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./XiaoBaWang-docs/build

  deploy:
    name: 部署到 GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4